//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BascketItem
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public double price { get; set; }
        public string BasketID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
